webform_shield.settings:
  type: config_object
  label: 'Webform Shield settings with enhanced security.'
  mapping:
    form_ids:
      type: sequence
      label: 'The protected form IDs'
      sequence:
        type: string
        label: 'The form ID'
    excluded_form_ids:
      type: sequence
      label: 'The form IDs that should never be protected'
      sequence:
        type: string
        label: 'The form ID'
    token_timeout:
      type: integer
      label: 'Token timeout in seconds'
    check_ip:
      type: boolean
      label: 'Check IP address for token validation'
    rate_limit_enabled:
      type: boolean
      label: 'Enable rate limiting for token requests'
    rate_limit_threshold:
      type: integer
      label: 'Rate limit threshold per hour per IP'
    rate_limit_excluded_ips:
      type: sequence
      label: 'IP addresses and subnets excluded from rate limiting'
      sequence:
        type: string
        label: 'IP address or subnet (CIDR notation)'
    log_security_events:
      type: boolean
      label: 'Log security events for monitoring'
    block_suspicious_requests:
      type: boolean
      label: 'Block suspicious requests'
    csrf_token_validation:
      type: boolean
      label: 'Require CSRF tokens for all requests'
    show_form_ids:
      type: boolean
      label: 'Show form IDs to admins'
    debug_mode:
      type: boolean
      label: 'Enable debug mode for development'